<?php

namespace XdebugBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * debugRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class debugRepository extends EntityRepository
{
}
